// <auto-generated />
using FrailynGarcia_AP1_P2.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FrailynGarcia_AP1_P2.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FrailynGarcia_AP1_P2.Models.Registros", b =>
                {
                    b.Property<int>("RegistroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegistroId"));

                    b.HasKey("RegistroId");

                    b.ToTable("Registros");
                });

            modelBuilder.Entity("FrailynGarcia_AP1_P2.Models.RegistrosDetalle", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleId"));

                    b.Property<int>("RegistroId")
                        .HasColumnType("int");

                    b.HasKey("DetalleId");

                    b.HasIndex("RegistroId");

                    b.ToTable("RegistrosDetalle");
                });

            modelBuilder.Entity("FrailynGarcia_AP1_P2.Models.RegistrosDetalle", b =>
                {
                    b.HasOne("FrailynGarcia_AP1_P2.Models.Registros", "Registros")
                        .WithMany("RegistrosDetalles")
                        .HasForeignKey("RegistroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registros");
                });

            modelBuilder.Entity("FrailynGarcia_AP1_P2.Models.Registros", b =>
                {
                    b.Navigation("RegistrosDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
